### ISSUE TITLE
Pagination is available with empty tables

### ISSUE THREAD

**Issue by neojp** [postlight/lux#102]
Even though my users table is empty I'm still able to paginate through the `links` provided in the listing.

![](https://i.gyazo.com/0f3fb771087a8ded790d4d9bfd22b62c.png)

**Comment by zacharygolba** [comment]
We probably still want to return a `200` status code and an empty array for `data` even if you exceed the maximum page but `null` values for `prev` and `next`.

```javascript
{
  data: [],
  links: {
    self: 'http://localhost:4000/users?page=1',
    first: 'http://localhost:4000/users?page=1',
    last: 'http://localhost:4000/users?page=1',
    prev: null,
    next: null
  }
}
```

**Comment by neojp** [comment]
Agreed.
