### ISSUE TITLE
Whitelist hidden files from globbing

### ISSUE THREAD

**Issue by neojp** [postlight/lux#103]
Renamed a controller to have a `.` in front of the file and caused the following error when running `lux serve`.

![](https://i.gyazo.com/f17795486311e1353dd76396e98aae7f.png)

This can pose a problem when using hidden files for custom linting `.eslintrc`, ignoring files `.gitignore` `.eslintignore` or even keeping an empty directory on git  `.gitkeep`

**Comment by zacharygolba** [comment]
You shouldn't rename controllers, models, or serializer's because they are resolved by file name to be dynamically loaded into your application.

This will not be an issue with `.eslintrc` or any other dot files as they are not in the controller/model/serializer directory.

**Comment by neojp** [comment]
I disagree. You are failing to see the point that hidden files exist regardless of how you create them, either manually or automatically because some sort of program created them for you. Like automatic backups or logs that you as a framework have no control over.

This can potentially affect your app because you are trying to include all files regardless of extension or hidden status.

**Comment by zacharygolba** [comment]
I think the real issue here is that the `loader` does not filter out non `.js` extensions. That doesn't mean that we should allow for models to be prefixed with `.`. Part of using a framework is conforming to it's opinions such as file naming conventions.

Can you create a new issue for filtering out any file that doesn't have `.js` extension in the loader package?

**Comment by neojp** [comment]
I think I've been misunderstood. I don't want you to let people access hidden files. It's the other way around. Ignore all files that have a `.` in front of the file name regardless of extension. And also ignore any other file that doesn't have a `.js` extension.

**Comment by zacharygolba** [comment]
That makes 100% sense. Can you write that in a new issue? 😃
