### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by paddythenerd** [postlight/lux#131]
Lux looks to be a very cool project, and I'm currently evaluating whether I can use it to build the core data APIs for my project. Kudos to a great effort thus far!

That said, I've gotten bitten following some outdated information in the wiki, most notably the first statement on the [Models](https://github.com/postlight/lux/wiki/Models) page:

> Models wrap a typical node-orm2 model in a ES2015 class to provide a more modern syntax.

It was only after a couple of days of R&D into `node-orm2` & things not working as I'd expect that I noticed in the commit log that node-orm2 had been replaced by an custom ORM wrapping `knex`.

I'm also finding myself reading through Lux's source code to determine whether some features I'll need are A) not (yet) implemented, or B) not documented well enough for me to figure out how to use them. It'd be really great to see JSDoc (or similar) incorporated into the source code and generated API docs.

If I decide I'm able to use Lux for my project, I'll be happy to contribute to that effort.

**Comment by zacharygolba** [comment]
Thank you! I appreciate you considering to use Lux for your project and I hope you do. :)

Docs are a real weak spot for us right now. I've been looking into JSDoc/YUIDoc recently and will tackle within the next 2 releases (on average that should be within 2 weeks). The wiki is outdated and hopefully can be replaced soon by gh pages soon.

In the mean time check out the [examples](https://github.com/postlight/lux/tree/master/examples) to see if you can use them as a reference. Also, I'm happy to answer any questions you have as the come up in our [Gitter](https://gitter.im/postlight/lux) room.

**Comment by zacharygolba** [comment]
Docs are currently live at [lux.postlight.com](https://lux.postlight.com).
