### ISSUE TITLE
Ensure Logger Stat Times Line Up

### ISSUE THREAD

**Issue by zacharygolba** [postlight/lux#259]
When stats are provided when a Lux application is running in the development environment stats do not always line up. This could potentially be because of a time having a greater number of digits than another.

It would be nice if all of the numbers lined up even if the digits vary from stat to stat.

![screen shot 2016-08-03 at 11 13 15 am](https://cloud.githubusercontent.com/assets/7378772/17370760/4c71649a-596b-11e6-9005-b370cfbd86d6.png)

**Comment by adampash** [comment]
Fixed in #292
