### ISSUE TITLE
Import alias for Lux applications

### ISSUE THREAD

**Issue by zacharygolba** [postlight/lux#272]
We should use [rollup-plugin-alias](https://github.com/frostney/rollup-plugin-alias) to allow for apps built with Lux to do the following:

```javascript
import { Controller } from 'lux-framework';

import Post from 'app/models/post';

class PostsController extends Controller {
  show({ params: { id } }) {
    return Post.find(id);
  }
}
```

Notice the `Post` Model is being imported from `app/models/post` rather than `../models/post`. This will be extremely beneficial once we introduce [router namespaces](https://github.com/postlight/lux/blob/master/ROADMAP.md#router-namespaces) since that involves more deeply nested directories.

**Comment by adampash** [comment]
Added in #293
