### ISSUE TITLE
Not able to pass ssl and port variables in database objects

### ISSUE THREAD

**Issue by harianus** [postlight/lux#290]
For Heroku example you have to connect via SSL. In urls this works like adding `?ssl=true` at the end. In Knex this works with the `connection` field.

I think it would be reasonable to have the `ssl: true` passed through from the `config/database.js` file to the Knex initiator. The same goes for `port: ...`, not sure it that does not work now.

```js
// config/database.js
development: {
  port: '5430', //     <-------
  host: '****',
  database: '****',
  password: '****',
  ssl: true, //        <-------
  username: '****',
  driver: 'pg',
  pool: { min: 0, max: 5 }
},
```

**Comment by zacharygolba** [comment]
The reason why `port` isn't working here is because it must be a `number` not a string. I'm going to leave this open because we still need to add the ability to pass a `boolean` `ssl`  option.

**Comment by adampash** [comment]
I mentioned this in #319, but port isn't working because it's not actually being included in the config yet. That PR should bring port and SSL support to the config.
