### ISSUE TITLE
Bad password practice in social-network example

### ISSUE THREAD

**Issue by such** [postlight/lux#351]
Hello,

I'm not a security expert but it seems that the password handling demonstrated in the social-network example should not be recommended. Indeed, if I understand correctly, it allows anyone with a dump of the database to compute easily the password of all users.
I get that it is not that big of a deal since it is only an example and not production code but it does not look good!

**Comment by zacharygolba** [comment]
Your absolutely right, I originally just wrote that as quick and dirty example. It would be nice to show something like integrating passport with Lux instead.

**Comment by such** [comment]
Hey,

I just made a small pull request addressing this issue: #371.
I sticked with a simple integration of bcrypt. I feel like some documentation on passport integration would be more valuable in the Wiki. Let me know what you think!

**Comment by zacharygolba** [comment]
👏 Awesome job! In the future we'll likely include passport integration on top of this. Thanks for helping out!
