### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by denzo** [postlight/lux#491]

**Comment by gentle-noah** [comment]
Yeah. They disappeared

**Comment by denzo** [comment]
I'm trying to figure out how to generate a model with relationships so the right migration is generated with it.

**Comment by nickschot** [comment]
Quoting @zacharygolba here from Gitter:

> a good trick to generate a resource is to add the attrs as well
> `lux g resource <name> […attrs]`
> Example:
> `lux g resource users name:string is-admin:boolean posts:has-many`
> that will generate a model, serializer, controller, migration, and update the routes.js file and write most of the boiler plate code for you

**Comment by denzo** [comment]
Cool thanks. After changing the model, adding more attributes or relationships for example, do I have to manually create or update a migration?

**Comment by zacharygolba** [comment]
@denzo you can use `lux g migration <name>` to generate an arbitrary migration.

Also, the docs are temporarily move to the source code as I'm working on integrating the docs into the Lux [website](https://lux.postlight.com). You can expect the docs to be back sometime in the next week.

cc @gentle-noah

**Comment by denzo** [comment]
Thanks so much. Lux looks really promising!

**Comment by gentle-noah** [comment]
@zacharygolba - let me know if you want any help with building out the docs pages on the Lux site. I have some free time in the evenings and don't mind writing mark up for hours on end.

**Comment by zacharygolba** [comment]
@gentle-noah thank you the docs site generator is already built and is currently undergoing an internal design review at Postlight. Help with the docs is greatly appreciated. Once the docs are live on the site we can split the missing docs up into issues and delegate the work accordingly. 😄 

Quick preview of the docs:

![screen shot 2016-10-30 at 6 06 46 pm](https://cloud.githubusercontent.com/assets/7378772/20151520/66bcb146-a688-11e6-9703-1de5e9272b37.png)

**Comment by nikitph** [comment]
is this live? i m new to lux and would really like to see the docs

**Comment by denzo** [comment]
Is there a way to access the preview of the docs?

**Comment by hugoruscitti** [comment]
wow, the docs preview looks great!, i want to help !!!

**Comment by zacharygolba** [comment]
@denzo @nikitph currently there is no way to access the docs site but we are actively working on it. In the mean time there are comments in the source code that ultimately determine the content of the docs. Also, feel free to ping me in our [Gitter room](https://gitter.im/postlight/lux) if you have any questions.

**Comment by zacharygolba** [comment]
@hugoruscitti Thanks! I may reach out to you sometime this week about that. There is a lot of work left to do in terms of writing guides and I have a plan that should allow us to knock it out quickly.

**Comment by zacharygolba** [comment]
@gentle-noah I may be reaching out to you as well. Keep an eye out on [Gitter](https://gitter.im/postlight/lux). 😃

**Comment by zacharygolba** [comment]
The docs are currently [live](https://lux.postlight.com)! Shout out to @darrellhanley for all the hard work 👏 .

There is still work to be done in code comments and writing better guides. If anyone is interested in contributing to that, let me know and I'll assign an issue associated with a section of the guide.
