### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by zacharygolba** [postlight/lux#51]

**Comment by kev5873** [comment]
We should add in instructions on how to run the framework locally for contributions/development.

**Comment by gentle-noah** [comment]
@zacharygolba @kev5873 - any progress on this? I would love to start contributing to the project. Have a few issues I have found in documentation + lots of ideas for generators.

**Comment by zacharygolba** [comment]
@gentle-noah Thanks for your interest in Lux! 😃 

We haven't made much progress on this issue but it's definitely a high priority.

I would love to hear your ideas for generators. Feel free to submit an RFC in the form of a GitHub issue. Also, if you wan't to make a contribution of any kind you are welcome to submit a PR.

If you have any questions, need general support, or just want to chat about an idea; send us a message in our [Gitter Room](https://gitter.im/postlight/lux).
