### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by nryoung** [postlight/lux#56]
This is extremely useful when troubleshooting bugs between versions or for people considering upgrading to a newer version.

This could probably wait until `lux` is out of beta, but I think it is important to include eventually.

**Comment by zacharygolba** [comment]
Ahh accidentally closed this instead of #52

**Comment by jhliberty** [comment]
@zacharygolba could use something like https://github.com/rvagg/changelog-maker
