### ISSUE TITLE
Not all requested ID's are returned when using filter[id]

### ISSUE THREAD

**Issue by nickschot** [postlight/lux#606]
**Note:** this is in my opinion _not_ a bug in Lux, but an interesting (and probably sensible) use case which is likely used by many Ember apps which might need some thought.

When using "filter" to request certain records (i.e. 1 through 50), not all requested ID's will be returned, only the first "page size" (25 by default). This causes Ember-data to fail because not all requested data is there.

Example URL (decoded) as created by Ember:
```
http://localhost:5000/my-resource?filter[id]=8679,8678,8677,8676,8675,8674,8673,8672,8671,8670,8669,8668,8667,8666,8665,8664,8663,8662,8661,8660,8659,8658,8656,8653,8652,8651,8650,8649,8648,8647,8646,8645,8644
```

Now this might be somewhat specific to Ember w/ `coalesceFindRequests = true` as it automatically retrieves relationships it needs based on ID's on the resources in this way. I'm not sure whether there is any control there over how many ID's it should provide per request, haven't found it yet. Ember-data also doesn't seem to grasp the concept of pagination without the page parameters and will not automatically retrieve the remaining pages.

Simple solution on the Ember side would be to turn off `coalesceFindRequests`, but this can/will cause a big amount of subsequent requests as then each ID is requested separately on the server.

**Comment by zacharygolba** [comment]
You can get around this in Ember with [`groupRecordsForFindMany`](http://emberjs.com/api/data/classes/DS.JSONAPIAdapter.html#method_groupRecordsForFindMany). Something like the following should work. I did not sanity check it though. 😉 

```javascript
import DS from 'ember-data';

const MAX_PER_PAGE = 25;

export default DS.JSONAPIAdapter.extend({
  coalesceFindRequests: true,

  groupRecordsForFindMany(store, snapshots) {
    const groups = [];
    const roundTotal = Math.ceil(arr.length / MAX_PER_PAGE) * MAX_PER_PAGE;

    for (let offset = 0; offset < roundTotal; offset += MAX_PER_PAGE) {
      groups.push(snapshots.slice(offset, offset + MAX_PER_PAGE));
    }

    return groups;
  }
});
```

**Comment by nickschot** [comment]
Didn't know that one yet! Should work great. Thanks!
