### ISSUE TITLE
Include parsed to string instead of array when a single include is used

### ISSUE THREAD

**Issue by nickschot** [postlight/lux#637]
Request URL like `GET "/my-resource?include%5B%5D=something"` which decoded is `GET "/my-resource?include[]=something"` is being parsed to:
```json
{
  "include": "something"
}
```
by Lux, which causes an error because it expects an array of strings.

When more include's are requested like `GET "/my-resource?include[]=something&include[]=else"` the include qp is correctly parsed to an array.

**Comment by nickschot** [comment]
I've tracked this down to node's `url.parse` method which generates `query: { 'include[]': 'myModel' }` when a single include is used and `query: { 'include[]': [ 'myModel', 'myOtherModel' }` when multiple includes are used. Lux doesn't do anything with the brackets next to the include (apart from stripping them) which is why this isn't working correctly. I think we should detect the type based on those brackets instead of relying on `url.parse` handling for arrays like this.

**Comment by nickschot** [comment]
This might not be a problem after all.... I had mistakenly interpreted `include` wrong in my client. It is a comma separated string instead of an array. So this fix might not be necessary!

cc @zacharygolba

**Comment by zacharygolba** [comment]
Your right @nickschot. The way Lux is parsing the query string is correct. See #640 for more information.
