### ISSUE TITLE
[docs] Minor clarity issue regarding afterAction result

### ISSUE THREAD

**Issue by nickschot** [postlight/lux#687]
The API docs regarding afterAction for controllers state that if a value is returned, that value will be used instead of the payload (result of the action). Currently Lux sends a 404 if nothing is returned from the afterAction method, so this is either a minor bug or a minor unclarity in the docs.

See: https://github.com/postlight/lux/blob/master/src/packages/controller/index.js#L409

**Comment by zacharygolba** [comment]
> Currently Lux sends a 404 if nothing is returned from the afterAction method

This is the intended result, the docs are confusing. The idea is after the action you are transforming the result to include something else. If you return nothing it is expected that was your intention which Lux maps to a `404` response.

Do you want to take on the doc updates @nickschot?

**Comment by nickschot** [comment]
Sure thing!
