### ISSUE TITLE
Controller afterAction not firing in production mode

### ISSUE THREAD

**Issue by nickschot** [postlight/lux#688]
*   **Platform**: macOS 10.12.4
*   **Database**: sqlite3 & postgres 9.6.x
*   **Lux Version**: 1.1.7
*   **Node Version**: 7.4.0 and 7.9.0

The afterAction hooks are not being fired in production mode while working fine in (normal) development mode. To reproduce add any function to the afterAction hook of (i.e.) the posts controller in the social-network example and send a GET request to `/posts`.

```javascript
afterAction = [
    (request, response, payload) => {
        console.log('AM I FIRING?');
        return payload;
    }
];
```

**Comment by nickschot** [comment]
It is of importance that the afterAction does end up in the bundle.

Snippet from compiled controller: 

```javascript
class PostsController extends Controller {
    constructor(...args) {
        var _temp;
        return _temp = super(...args), this.params = ['user', 'body', 'title', 'isPublic'], this.afterAction = [
            (a, b, c) => {
                return console.log('AM I FIRING?'), c
            }
        ], _temp
    }
}
```

**Comment by nickschot** [comment]
I've tracked this down to having something to do with _babili_ . When disabling babili in babel-preset-lux, afterAction get's triggered.

**Comment by nickschot** [comment]
Babili has some open issues related to variables disappearing in for loops.

Might be better to disable or replace babili for now?

**Comment by zacharygolba** [comment]
Nice detective work @nickschot!

> Might be better to disable or replace babili for now

I think that's a good idea.

If you want to take this on, updates should be made to [babel-preset-lux](https://github.com/postlight/babel-preset-lux/blob/master/index.js#L14-L16). Also, you may be able to add `"minified": false` to your `.babelrc` to prevent this from occurring for the time being.

**Comment by nickschot** [comment]
Do you want to replace it with the old uglify or just disable babili? There was some note that uglify undoes some optimisations made by Babel.

**Comment by zacharygolba** [comment]
I think we could just remove babili until it becomes more stable. IMO, the minification is a micro optimization that we can live without.
