### ISSUE TITLE
Route-specific content-type headers

### ISSUE THREAD

**Issue by willviles** [postlight/lux#692]
At present, Lux only accepts `application/vnd.api+json` content types. For example, sending a POST request with `content-type` header set to `application/x-www-form-urlencoded`, results in a 400 Bad Request error:

```json
{
  "errors": [
    {
      "status": "400",
      "title": "Bad Request",
      "detail": "Content-Type: 'application/x-www-form-urlencoded' is not supported. Try your request again with Content-Type: 'application/vnd.api+json'."
    }
  ],
  "jsonapi": {
    "version": "1.0"
  }
}
```
#### Problem
I need both a password + refresh token auth flow and also a Facebook auth flow, so I'm currently attempting to build a robust OAuth2 solution for Lux on top of [node-oauth2-server](https://github.com/oauthjs/node-oauth2-server). 

Unfortunately, OAuth2 specification demands POST requests are sent as `application/x-www-form-urlencoded` and [node-oauth2-server](https://github.com/oauthjs/node-oauth2-server) specifically validates that all requests are `application/x-www-form-urlencoded`.

#### Proposed Solution

1. Make Lux server's [validateRequest](https://github.com/postlight/lux/blob/9e2f84bd2d0675023b694a154b01f0b28604206e/src/packages/server/index.js#L88-L96) route-aware.
2. Add an options hash as a third param to a route action. Example:
```js
this.resource('oauth', {
  only: []
}, function(){
  this.post('/token', 'token', { contentType: 'application/x-www-form-urlencoded' });
});
```
3. Ensure any requests without content type set to `application/vnd.api+json` skips serialization and any other JSONAPI specific methods.

**Comment by nickschot** [comment]
I like the proposed solution. Simpler and more clear than modifying the res obj in the controller.
