### ISSUE TITLE
Getting undefined field name in related model query

### ISSUE THREAD

**Issue by robnauticus** [postlight/lux#696]
Simple project created below:
```
call lux g resource estimates estimatename:string estimatecode:string items:has-many

call lux g resource items itemname:string itemcode:string estimates:belongs-to costs:has-many

call lux g resource costs costtype:string costamount:decimal costunits:decimal costuom:string items:belongs-to

call lux db:create

call lux db:migrate
```

Once built and served without apparent issue, see below what happens when I send a new estimate.
It gets created in the db but the query following up with the relationship (items) errors with an undefined field name somehow. I haven't made any changes to the controllers, models or serializers either. 

Could it be something to do with there being no records? I'm going to try and seed a few records to see if that helps.

Just getting the hang of Lux but enjoying it's "Ember-ness". Thanks!

```

[2017-05-11T01:29:37.751Z] INSERT INTO "estimates" ("created_at", "estimatecode", "estimatename", "updated_at") VALUES ('2017-05-10 18:29:37.743', '5', 'EST 5', '2017-05-10 18:29:37.743')

------------------------------------------------------------------------------------------------------------------------

[2017-05-11T01:29:37.785Z] SELECT "items"."id" AS "id", "items"."itemname" AS "itemname", "items"."itemcode" AS "itemcode", "items"."estimates_id" AS "estimatesId", "items"."created_at" AS "createdAt", "items"."updated_at" AS "updatedAt" FROM "items"

------------------------------------------------------------------------------------------------------------------------

[2017-05-11T01:29:37.791Z] TypeError: Cannot match against 'undefined' or 'null'.
    at setHasManyInverse (C:\Users\rob\Documents\GitHub\baseestimating-lux\dist\bundle.js:284:177)
    at setHasMany (C:\Users\rob\Documents\GitHub\baseestimating-lux\dist\bundle.js:286:501)
    at set$1 (C:\Users\rob\Documents\GitHub\baseestimating-lux\dist\bundle.js:290:224)
    at C:\Users\rob\Documents\GitHub\baseestimating-lux\dist\bundle.js:290:1086
    at Generator.next (<anonymous>)
    at step (C:\Users\rob\Documents\GitHub\baseestimating-lux\dist\bundle.js:68:30)
    at C:\Users\rob\Documents\GitHub\baseestimating-lux\dist\bundle.js:79:13

------------------------------------------------------------------------------------------------------------------------

[2017-05-11T01:29:37.794Z] Processed POST "/estimates" from ::1 with 500 Internal Server Error by EstimatesController#create

Params

{
  "data": {
    "type": "estimates",
    "attributes": {
      "estimatename": "Est 5",
      "estimatecode": "5"
    },
    "relationships": {}
  }
}

Stats


 0 ms Total
71 ms Actual
```

*   **Windows 10**:
*   **Sqlite**:
*   **Lux Version 1.1.7**:
*   **Node Version 7.9.0**:

**Comment by robnauticus** [comment]
If I GET /items

```
[2017-05-11T01:52:31.469Z] SELECT COUNT(*) AS "countAll" FROM "items"

------------------------------------------------------------------------------------------------------------------------

[2017-05-11T01:52:31.474Z] SELECT "costs"."id" AS "id", "costs"."undefined" AS "undefined" FROM "costs"

------------------------------------------------------------------------------------------------------------------------

(node:16068) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: select "costs"."id" as "id", "costs"."undefined" as "undefined" from "costs" - SQLITE_ERROR: no such column: costs.undefined
(node:16068) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jamemackson** [comment]
@robnauticus I would start by checking that the relationship names and related links in your models all match up.  In my experience this is usually to blame for undefined creeping into queries etc like this.  I'm hoping to write a eslint plugin to check for these kinds of things, cause they are maddening, but haven't yet found the time to do it. :(

**Comment by robnauticus** [comment]
@jamemackson Thanks for getting back.
I used the command line tool to generate the model, serializer and controller for the three resources. I checked the names in the batch file I created to generate it. Makes me think there is something else going on (possibly in the Lux generation scripts) as I can reproduce this in a new project with or without seeded data. I can also generate the resources without relationships and can create/list as expected. HTH!

**Comment by jamemackson** [comment]
np.  I *think* there is a bug in those generation scripts but haven't taken the time to nail that down... I suspect we need to ensure the right things are singularized/pluralized in there.  one thing I have had to pay close attention to is that `belongsTo` relationship `inverse` properties are all plural. 

Were you able to get your request working with your relationships in place?

**Comment by robnauticus** [comment]
Not yet. I will dig into the relationships that were generated and pay attention to the pluralized field names. I'll let you know. Thanks again!

**Comment by robnauticus** [comment]
I pluralized the Inverse property of the relationships in the Model objects. It is working now! :)

**Comment by jamemackson** [comment]
Glad to hear it 👍
