### ISSUE TITLE
Docker help

### ISSUE THREAD

**Issue by gbailey4** [postlight/lux#72]
I've been banging my head against a wall trying to run lux in docker. Do you happen to have a docker/docker-compose setup that you use? If not, I can keep trying to "dockerize" this.

**Comment by jhliberty** [comment]
What part are you getting stuck on exactly?

**Comment by gbailey4** [comment]
Having a hard time generating "lux new" in the container. Have you been able to do that?

**Comment by zacharygolba** [comment]
Is the `lux` command accessible from the containers `$PATH` (i.e did you `npm install -g lux-framework`)? I don't have a ton of experience with docker so bear with me haha.

**Comment by philipforget** [comment]
@gbailey4 Here's a simple Dockerfile that installs bash, node, npm, and lux. You can drop into a shell from it and play with lux from there

```Dockerfile
FROM alpine:latest

RUN apk update && \
    apk add --no-cache \
    bash \
    nodejs \
    && rm -rf /var/cache/apk/*

RUN npm install -g lux-framework

CMD ['/bin/bash']
```

**Comment by philipforget** [comment]
@zacharygolba let me know if you want to get an official Dockerfile going for easier testing / playing around. I'll gladly put in a PR.

**Comment by zacharygolba** [comment]
@philipforget great idea! I'm closing this in favor of #73. 😃

**Comment by gbailey4** [comment]
@philipforget thank you for your help in pointing me in the right direction!

**Comment by philipforget** [comment]
No problem! Let me know if you have any more docker questions
