### ISSUE TITLE
Updating hasMany => through relationships

### ISSUE THREAD

**Issue by willviles** [postlight/lux#720]
Platform: Darwin Kernel Version 16.7.0
Database: Tested w/SQLite3 & pg (assumed present on all dbs)
Lux Version: 1.2.1
Node Version: 6.10

To replicate this error, use the Lux test app inside the Lux repo.

1) Add `reactions` and `tags` to [app/controllers/posts.js](https://github.com/postlight/lux/blob/v1.2.1/test/test-app/app/controllers/posts.js) params.
2) Ensure the database is migrated and seeded. Run lux serve inside [test/test-app](https://github.com/postlight/lux/tree/v1.2.1/test/test-app)
3) Send a PATCH to `/posts/1` with the following body to confirm `reactions` update properly:
```json
{
	"data": {
		"id": "1",
		"type": "posts",
		"attributes": {
		},
		"relationships": {
			"reactions": {
				"data": [{
					"id": "1",
					"type": "reactions"
				}]
			}
		}
	}
}
```
4) Send a PATCH to `/posts/1` with the following body:
```json
{
	"data": {
		"id": "1",
		"type": "posts",
		"attributes": {
		},
		"relationships": {
			"tags": {
				"data": [{
					"id": "1",
					"type": "tags"
				}]
			}
		}
	}
}
```
5) The following error should be logged: `Error: SQLITE_ERROR: no such column: post_id`.

It appears Lux is trying to update the relationship as though there's no joining `categorization` resource.

**Comment by willviles** [comment]
Also, to get `lux seed` to work in the test app, I had to make a slight amendment to [/test/test-app/db/seed.js](https://github.com/postlight/lux/blob/master/test/test-app/db/seed.js#L5). `connection` is undefined, so `trx.batchInsert()` throws an error. The following code ran the seeds successfully:

```js
import __fixtures__ from './__fixtures__.json'

const CHUNK_SIZE = 100

export default async function seed(trx) {
  const promises = Object
    .keys(__fixtures__)
    .map(key => [
      key,
      __fixtures__[key].map(row => (
        Object.assign(row, {
          created_at: new Date(row.created_at),
          updated_at: new Date(row.updated_at),
        })
      ))
    ])
    .reduce((arr, [table, rows]) => {
      arr[arr.length] = trx
        .batchInsert(table, rows, CHUNK_SIZE)
        .transacting(trx)
      return arr
    }, [])

  return Promise.all(promises)
}
```

**Comment by zacharygolba** [comment]
@willviles I was able to reproduce your issue regarding updating has many through relationships. I'm going to look into this a bit deeper and see if there is an easy fix.

In the mean time, could you expose the `through` model's controller and modify the relationships from there? I confirmed that it is working in the in `v1.2.1`.

#### Add Relationship 

```http
POST /friendships HTTP/1.1
Content-Type: application/vnd.api+json
Content-Length: 282

{
  "data": {
    "type": "friendships",
    "relationships": {
      "follower": {
        "data": {
          "id": ":id",
          "type": "users"
        }
      },
      "followee": {
        "data": {
          "id": ":id",
          "type": "users"
        }
      }
    }
  }
}
```

#### Remove Relationship

```http
DELETE /friendships/:id HTTP/1.1
```
