### ISSUE TITLE
Relationship with falsy ID (i.e. 0) not serialized

### ISSUE THREAD

**Issue by nickschot** [postlight/lux#729]
*   **Platform**: macOS 10.13
*   **Database**: postgres 9
*   **Lux Version**: 1.2.2
*   **Node Version**: 9

There are two problems causing relationships with `0` as it's ID not to be handled correctly. 

1. https://github.com/postlight/lux/blob/7bf2478bd0305d65549f9b9fe98997f51dc07ae0/src/packages/database/query/runner/utils/build-results.js#L112  here relationships fall through when the value is 0 (because it's falsy of course) and thus aren't put into the Model instance properly.

2.  https://github.com/postlight/lux/blob/7bf2478bd0305d65549f9b9fe98997f51dc07ae0/src/packages/serializer/index.js#L629 here the relationships are only formatted when the relationship ID isn't falsy.

For both I suspect checking if the value is either `null` or `undefined` is enough.

**Comment by nickschot** [comment]
@zacharygolba if you could confirm this bug and fix I'll whip up a small PR for it. Would be awesome if a minor release could be published to solve this.

**Comment by zacharygolba** [comment]
@nickschot thank you for this detailed issue. This is very helpful! 😃

> For both I suspect checking if the value is either null or undefined is enough.

I agree. Checking for `null` with loose equality feels like the right solution here.

> if you could confirm this bug and fix, I'll whip up a small PR for it. Would be awesome if a minor release could be published to solve this.

This is definitely a bug, feel free to submit a PR. I would be happy to cut a release once this is resolved. As always, your help is greatly appreciated!

**Comment by zacharygolba** [comment]
Fixed in [v1.2.3](https://github.com/postlight/lux/releases/tag/v1.2.3)
