### ISSUE TITLE
include nested relationship

### ISSUE THREAD

**Issue by jonathanpruvost** [postlight/lux#748]
Hello,

Even if it no longer seems to be maintained, I try my luck.

I'm having a problem when trying to include a relation from a relation like in the ember-data usage example:
`include: 'comments,comments.author'`
https://guides.emberjs.com/release/models/relationships/#toc_retrieving-related-records

I receive a 400 error, Bad request, Is this possible with Lux?

Thank you for your help.

**Comment by nickschot** [comment]
Unfortunately Lux has no support for nested includes, even top level includes are not complete as they do not include relationships and, in the case of ember-data, will make ember-data believe the relationships are null.

**Comment by jonathanpruvost** [comment]
thank you for your reply
