### ISSUE TITLE
cli to check existing files

### ISSUE THREAD

**Issue by dowsanjack** [postlight/lux#82]
The CLI should check for existing files when generating the file with the same name and ask for user input before replacing any, with the option to skip if they deny the permission.

**Comment by neojp** [comment]
Also, new migration files are created when generating a model with the same name throwing errors when running `lux db:migration` because tables already exist (using mysql).

**Comment by zacharygolba** [comment]
Thanks @dowsanjack, @neojp! I'll work on a fix for this in the next release `0.0.1-beta.10`. 😃
