### ISSUE TITLE
Generate `resource` task on CLI

### ISSUE THREAD

**Issue by neojp** [postlight/lux#98]
It would be nice if there was a task that batches editing the routes.js, creates the controller, model and serializer.
```
lux generate resource user
```

**Comment by zacharygolba** [comment]
This exists already. Also you can pass attrs as arguments to autofill out your files! 😃 

##### Example:
`lux g resource task name:string is-completed:boolean due-date:datetime list:belongs-to`

**Comment by neojp** [comment]
Completely missed it when reading through the docs and git log D:

**Comment by zacharygolba** [comment]
Our docs need some work. We recently had a pretty massive PR merge and some APIs have changed. 

If you need any good resources for examples, [reference the todo app in the `update-examples` branch](https://github.com/postlight/lux/tree/update-examples/examples/todo).

Also, @jhliberty has done some [pretty amazing work](https://github.com/terminalvelocity/illumine) on some examples working with Ember.

**Comment by zacharygolba** [comment]
Also, if you have any questions feel free to jump in our [Gitter](https://gitter.im/postlight/lux) chat room and ask! 😃
