### ISSUE TITLE
Autogenerate controllers and serializers on the fly

### ISSUE THREAD

**Issue by neojp** [postlight/lux#99]
At the moment you require a route, controller, model and a serializer to exist to be able to return some sort of content.

From the README.md
> Automatic CRUD actions in controllers
> Automatic pagination, sorting, filtering via query params in controllers

I misunderstood this by thinking controllers and serializers where autogenerated on the fly the way it works on Ember (Ember spoils you). And there weren't any good error messages when they didn't exist.

Would definitely consider these files optional since they work by being empty. Eg.

```
import { Controller } from 'lux-framework';

class UsersController extends Controller {

}

export default UsersController;
```

**Comment by zacharygolba** [comment]
I definitely understand how this could be confusing so thanks for posting this issue however, It would be extremely insecure to auto-generate these on the backend as they could accidentally expose sensitive information from your db (such as credit card info) 😱.

Although the controllers work when they are empty it is encouraged that you at least fill out what can and can't be modified from the outside in controllers via the `params<Array>` property. Serializers always require you to explicitly set what can be accessed from the client so they are required to be filled out no matter what.

> And there weren't any good error messages when they didn't exist.

This is a great point. I'm going to close this issue for now but could you create another for having a more helpful error when a particular resource is missing a controller, route, serializer, etc?

Thanks for your help 😃.
